### ISSUE TITLE
mate-control-center scrollbar is not updated after removing search results

### ISSUE THREAD

**Issue by hiboudev** [mate-desktop/mate-control-center#216] opened 2016-01-05 23:05 UTC
Issue in Linux Mint 17.3 with Mate 1.12.0 (32 bits)

* How to reproduce:
In mate-control-center, resize vertically the window to activate the vertical scrollbar, so you can use it to scroll the view.
Do a search, for example with "net", then select all the search and delete it.

* The bug:
All icons are now displayed, but the scrollbar did not refresh, so you can't navigate to the hidden icons.
It seems the scrollbar refresh fine when adding text in the search box, but not when removing text.

* What is expected:
The scrollbar should be refreshed every time the icons view is refreshed.

* How to fix it temporarily:
Resize the window and the scrollbar is refreshed.

**Comment by raveit65** [comment] 2016-01-05 23:16
Did you filed out a report against your distro?
To be shure that isn't a distro issue.

**Comment by monsta** [comment] 2016-01-06 19:22
I can't reproduce it in the same Mint release but with latest m-c-c from master.
But I suspect this is related to https://github.com/mate-desktop/mate-control-center/issues/160 which is fixed in https://github.com/mate-desktop/mate-control-center/commit/3b172c9761653f635a979f97dcc9ff74e896f40f. I'll ask @clefebvre to push 1.12.1 to Mint repos.

**Comment by hiboudev** [comment] 2016-01-06 23:13
raveit65 : No, I was in doubt and someone on Mint IRC convinced me to report first here. And I saw that I use latest Mate version.

One detail : after I deleted the search items in one time (select all and delete), the scrollbar is not displayed at all. But if I delete one letter after another, it seems to bug (no scroll bar) only the first time the scroll bar should be displayed, and for the next deleted letters it works fine.

**Comment by raveit65** [comment] 2016-01-06 23:42
> No, I was in doubt and someone on Mint IRC convinced me to report first here
In general:
Please file out first a report against your distro, than your distro maintainer can check if the issue is disto related.
And than here.
If all Mate users from all distros post here first than i add mate github to my spam filter.
Sorry, but distros like Linuxmint without a bugzilla page forcing us to do their work.
Most other distros have their own BZ pages an users report first there.

**Comment by hiboudev** [comment] 2016-01-07 14:15
OK Raveit65, I'll know it for the future. I reported it to Mate Mint team.

**Comment by monsta** [comment] 2016-03-25 08:03
@hiboudev: m-c-c 1.12.1 with the fix is in Mint 17.3 repos now, please test it.

**Comment by hiboudev** [comment] 2016-03-26 13:51
@monsta I just tested it and this bug seems fixed. Thank you for your work!

**Comment by monsta** [comment] 2016-03-26 14:20
Ok good :smile:

**Closed by monsta** 2016-03-26 14:20 UTC
