### ISSUE TITLE
Mate display segmentation fault when detecting HDMI monitor

### ISSUE THREAD

**Issue by orland0m** [mate-desktop/mate-control-center#123] opened 2014-10-11 14:11 UTC
I was having trouble getting my HDMI monitor detected. After a few tries it worked but it would it left behind segmentation fault messages:
```
$ dmesg | grep mate
[   67.238789] mate-display-pr[1077]: segfault at 8 ip 00007f1986b6d74d sp 00007fff18443690 error 4 in libgdk-x11-2.0.so.0.2400.24[7f1986b14000+b0000]
[  772.351928] mate-display-pr[1638]: segfault at 4 ip 0000000000000004 sp 00007fff3a5240c8 error 14 in mate-display-properties[400000+f000]
[ 1084.133287] mate-display-pr[1699]: segfault at 8 ip 00007fc4863fd74d sp 00007fffe5feb870 error 4 in libgdk-x11-2.0.so.0.2400.24[7fc4863a4000+b0000]
```

Steps to reproduce:
* System -> Preferences -> Monitors
* Connect HDMI monitor
* Monitors app crashes. If it didn't clicking 'Detect' made it crash.
* After a few seconds the monitor was detected and is working normally.

```
$ uname -a
Linux arch 3.16.4-1-ARCH #1 SMP PREEMPT Mon Oct 6 08:22:27 CEST 2014 x86_64 GNU/Linux
$ sudo pacman -Ss mate | grep installed
community/atril 1.8.1-1 (mate-extra) [installed]
community/caja 1.8.2-1 (mate) [installed]
community/caja-gksu 1.8.0-3 (mate-extra) [installed]
community/caja-image-converter 1.8.0-3 (mate-extra) [installed]
community/caja-open-terminal 1.8.0-3 (mate-extra) [installed]
community/caja-sendto 1.8.0-3 (mate-extra) [installed]
community/caja-share 1.8.0-3 (mate-extra) [installed]
community/engrampa 1.8.1-1 (mate-extra) [installed]
community/eom 1.8.1-1 (mate-extra) [installed]
community/galculator-gtk2 2.1.3-3 (mate-extra) [installed]
community/gnome-main-menu 1.8.0-1 [installed]
community/libmatekbd 1.8.0-1 [installed]
community/libmateweather 1.8.0-1 [installed]
community/marco 1.8.2-1 (mate) [installed]
community/mate-applets 1.8.1-1 (mate-extra) [installed]
community/mate-backgrounds 1.8.0-1 (mate) [installed]
community/mate-color-manager 1.8.0-1 [installed]
community/mate-control-center 1.8.3-1 (mate) [installed]
community/mate-desktop 1.8.1-2 (mate) [installed]
community/mate-dialogs 1.8.0-2 (mate) [installed]
community/mate-icon-theme 1.8.0-1 (mate) [installed]
community/mate-icon-theme-faenza 1.8.0-1 (mate-extra) [installed]
community/mate-media-pulseaudio 1.8.0-3 (mate-extra) [installed]
community/mate-menus 1.8.0-1 (mate) [installed]
community/mate-netspeed 1.8.0-2 (mate-extra) [installed]
community/mate-notification-daemon 1.8.0-1 (mate) [installed]
community/mate-panel 1.8.1-1 (mate) [installed]
community/mate-polkit 1.8.0-1 (mate) [installed]
community/mate-power-manager 1.8.1-2 (mate-extra) [installed]
community/mate-screensaver 1.8.1-1 (mate-extra) [installed]
community/mate-screensaver-hacks 5.26-1 [installed]
community/mate-sensors-applet 1.8.0-4 (mate-extra) [installed]
community/mate-session-manager 1.8.1-3 (mate) [installed]
community/mate-settings-daemon-pulseaudio 1.8.2-1 (mate) [installed]
community/mate-system-monitor 1.8.0-2 (mate-extra) [installed]
community/mate-terminal 1.8.1-1 (mate-extra) [installed]
community/mate-themes 1.8.1-1 (mate) [installed]
community/mate-themes-extras 1.9.1-2 [installed]
community/mate-user-share 1.8.0-2 (mate-extra) [installed]
community/mate-utils 1.8.1-1 (mate-extra) [installed]
community/mozo 1.8.0-1 (mate-extra) [installed]
community/pluma 1.8.1-1 (mate-extra) [installed]
$ lspci
00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.1 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM76 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
01:00.0 Ethernet controller: Qualcomm Atheros AR8161 Gigabit Ethernet (rev 10)
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723AE PCIe Wireless Network Adapter
```

**Comment by stefano-k** [comment] 2015-02-06 13:03
Duplicate of https://github.com/mate-desktop/mate-control-center/issues/48

**Closed by stefano-k** 2015-02-06 13:03 UTC
Labels: unconfirmed
