### ISSUE TITLE
GTK+3: mate-font-viewer shows blank window

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-control-center#144] opened 2015-02-12 12:30 UTC
VirtualBox, Debian Testing, GTK+3 build of MATE 1.9 (all packages are from git master), GTK+ 3.14.5.

![bad-font-viewer](https://cloud.githubusercontent.com/assets/5138986/6167394/0007d25c-b2cc-11e4-9161-1ecfcd1ba915.png)

**Comment by NiceandGently** [comment] 2015-06-20 13:15
confirmed,
mate-font-viewer /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf
shows nothing.

**Comment by NiceandGently** [comment] 2015-06-29 10:06
this can be fixed by those commits.
https://git.gnome.org/browse/gnome-font-viewer/commit/?h=gnome-3-4&id=51110f87d6f134f8481031f13fdc3bc3759991bb
https://git.gnome.org/browse/gnome-font-viewer/commit/?h=gnome-3-4&id=b455a7fbb4d601e603d377e48ad324bc69cda162
In summary, the port it to GTK+3/cairo rendering is missing

**Comment by NiceandGently** [comment] 2015-08-08 17:35
this is a resuting patch from gnome commits
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/mate-control-center_font-viewer-3.patch
but you won't like this because a lot can be droped from the patch and i don't know if it breaks gtk2 build.
But for a work presentation it is good enough.

**Comment by infirit** [comment] 2015-08-08 18:27
It will break Gtk3 as it removes the expose_event handling, it also introduces some deprecated stuff I already got rid of but.. after that there is little in there Gtk3. Here is your patch with these things cleaned up. Totally untested except that it builds :wink:.

https://github.com/infirit/mate-control-center/commit/278301ec15b9f0df71184baf91ef5f0c10e3eb08

**Comment by infirit** [comment] 2015-08-20 18:26
https://github.com/mate-desktop/mate-control-center/commit/11a458806bf0775b663c164dfc1403f1f3947784

**Closed** 2015-08-20 18:26 UTC
Labels: confirmed
