### ISSUE TITLE
Height bug

### ISSUE THREAD

**Issue by s-chizhik** [mate-desktop/mate-control-center#160] opened 2015-06-24 05:42 UTC
Hi. My conf:

    OS: Ubuntu 14.04
    Package: mate-control-center
    Version: 1.8.3+dfsg1-2~trusty1
    MD5sum: c5e283dad3659bcf1a89fc73cc90a43d

Default size:
![default size]
(http://oi62.tinypic.com/4jrubn.jpg)

Full size:
![full size]
(http://oi60.tinypic.com/axcg2e.jpg)

As you can see, in default size at the bottom some items are cutted.

**Comment by NiceandGently** [comment] 2015-06-29 09:52
But you can scroll the window to see the other items in default size.

**Comment by monsta** [comment] 2015-07-01 09:27
I could reproduce this all the time in my LMDE (Linux Mint Debian Edition) with 1.8, and still can reproduce with 1.10. Resizing the window (in any direction) makes the issue go away. It comes back on the next m-c-c run though.

**Comment by infirit** [comment] 2015-07-01 10:20
Can't confirm, does it also happen with Menta and TraditionalOk? Or maybe it is screen resolution related, I run at 1920x1080.

**Comment by monsta** [comment] 2015-07-01 10:30
I normally use Mint-X theme, but yes, it also happens with Menta and TraditionalOk.
My screen resolution is 1280x1024.

**Comment by infirit** [comment] 2015-07-01 11:06
Tried in a jessie virtualbox vm and can't reproduce..

**Comment by s-chizhik** [comment] 2015-07-01 20:08
Sorry, forgot. I using laptop with resolution 1366x768

**Comment by monsta** [comment] 2015-07-02 09:38
> Tried in a jessie virtualbox vm and can't reproduce..

Same here - reproducible only on a real machine. Not sure if this could be related, but it has nvidia card and proprietary drivers installed.

**Comment by monsta** [comment] 2015-12-01 08:06
Hmm, https://github.com/mate-desktop/mate-control-center/issues/208 is a duplicate of this... anyway, it's fixed now in https://github.com/mate-desktop/mate-control-center/commit/c0a4fef81cbad7f0f174f57baffaf14fbc556142.

**Closed by monsta** 2015-12-01 08:06 UTC
Labels: unconfirmed
