### ISSUE TITLE
Mate Font Viewer only displays only one of the sub-font when opened a Super OTC font

### ISSUE THREAD

**Issue by Vdragon** [mate-desktop/mate-control-center#118] opened 2014-09-23 15:38 UTC
Refer: https://code.google.com/p/noto/issues/detail?id=158
## Current behavior

mate-font-viewer seems to only display the first font found in the file
## Expected behavior

UI listed multiple fonts if the file actually contains multiple fonts.
## mate-control-center

Self-compiled 1.8.1 
##

**Comment by monsta** [comment] 2017-01-06 17:46
Confirmed with NotoSansCJK. We can probably pick TrueType Collection support from the commits referenced in https://bugzilla.gnome.org/752005.

**Comment by monsta** [comment] 2017-03-09 13:26
Ok, it seems to be fixed now that @raveit65 picked these commits.

Before (at commit a0971f5):

![noto-sans-sucks](https://cloud.githubusercontent.com/assets/5138986/23752010/1ac272e4-04ed-11e7-9571-de944876f8d9.png)

After (at commit 598aa84):

![noto-sans-cjk](https://cloud.githubusercontent.com/assets/5138986/23752025/2960c0c6-04ed-11e7-9ed3-f039c5e347f4.png)

So it now shows CJK KR, SC, TC variants, and no duplicate items for JP one. I guess this is the requested feature.

**Closed by monsta** 2017-03-09 13:26 UTC
