### ISSUE TITLE
mate-display-properties bug when drag displays

### ISSUE THREAD

**Issue by ftoledo** [mate-desktop/mate-control-center#673] opened 2021-10-24 22:32 UTC
#### Expected behaviour
drag displays and arrange it

#### Actual behaviour

drag displasy show overlaped images

#### Steps to reproduce the behaviour
open mate-display-properties and drag displays

#### MATE general version
1.20.4

#### Package version

ragnarok@ragnarok:~$ apt-cache policy mate-control-center
mate-control-center:
  Instalados: 1.20.4-2
  Candidato:  1.20.4-2
  Tabla de versión:
 *** 1.20.4-2 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

#### Linux Distribution

Debian buster

![imagen](https://user-images.githubusercontent.com/95441/138615579-b8c63e86-9808-4131-b313-bedbe6fa9817.png)

**Comment by N0rbert** [comment] 2021-12-27 16:00
Got this issue on Ubuntu MATE 22.04 LTS daily ISO, we have the following downstream bug-report - https://bugs.launchpad.net/ubuntu/+source/mate-control-center/+bug/1934752 .

**Comment by mbkma** [comment] 2021-12-27 22:47
Duplicate of https://github.com/mate-desktop/mate-control-center/issues/273

**Closed by mbkma** 2021-12-27 22:47 UTC
Labels: confirmed

**Comment by lukefromdc** [comment] 2021-12-27 23:11
I just confirmed that I am still NOT getting this problem on Debian Unstable with locally built MATE 1.26

**Comment by ftoledo** [comment] 2021-12-28 14:47
I cannot reproduce anymore at debian buster with same mate-control-center version, so i think that some gtk libs updates was fixed this issue as #273 
current gtk lib version: 
libgtk-3-0:amd64 3.24.5-1    
thanks!
