### ISSUE TITLE
cannot set primary display

### ISSUE THREAD

**Issue by cheater** [mate-desktop/mate-control-center#17] opened 2012-11-10 09:34 UTC
mate insists on using my laptop's tiny display, rather than the big external one, as the primary monitor. This makes a dual-monitor setup completely unusable, as I can't even see the icons from where I'm sitting. I can work around this by turning off the laptop's monitor.

A more advanced workaround which lets me use both monitors is to log out, edit ~/.config/monitors.xml setting the LVDS display's primary tag to no, and the HDMI display's to on. Then log back into mate. If I do this while in mate it doesn't work, it's probably that the settings daemon only reads the file at startup.

Expected functionality: a drop-down box in the monitor applet which selects the primary monitor. No, having to turn off a monitor and turn it on again doesn't cut it, as it is non-obvious, bad UX, and not discoverable.

I am on Ubuntu 12.04 with the latest mate from ppa.

**Comment by mirkoperillo** [comment] 2015-01-13 11:13
I confirm the same problem with my laptop and an external monitor with ubuntu-mate 14.04 LTS (mate 1.8.1).

Resolved editing ~/.config/monitors.xml and doing login again.

In unity on ubuntu 12.04 there is in monitors panel a dropbox menu to permit to show launcher on one of available monitors or on both, something like  that can be useful

**Comment by mirkoperillo** [comment] 2015-01-21 12:47
Another thing about,

I modified monitors.xml with success, but sometimes when I switch on my pc, mate-panel is on my laptop screen either than on external monitor and monitors.xml presents a new configuration tag in append..something like this

```xml
<monitors version="1">
  <configuration>
      <clone>no</clone>
      <output name="eDP1">
          <vendor>CMN</vendor>
          <product>0x15ba</product>
          <serial>0x00000000</serial>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
          <x>1920</x>
          <y>120</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="VGA2">
          <vendor>DEL</vendor>
          <product>0xa079</product>
          <serial>0x3145524c</serial>
          <width>1920</width>
          <height>1200</height>
    <rate>60</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>yes</primary>
      </output>
      <output name="HDMI1">
      </output>
      <output name="DP1">
      </output>
      <output name="HDMI2">
      </output>
      <output name="DP2">
      </output>
      <output name="HDMI3">
      </output>
      <output name="VIRTUAL1">
      </output>
      <output name="VGA-1-0">
      </output>
  </configuration>
 <configuration>
      <clone>no</clone>
      <output name="eDP1">
          <vendor>CMN</vendor>
          <product>0x15ba</product>
          <serial>0x00000000</serial>
          <width>1920</width>
          <height>1080</height>
          <rate>60</rate>
          <x>1920</x>
          <y>120</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="VGA1">
          <vendor>DEL</vendor>
          <product>0xa079</product>
          <serial>0x3145524c</serial>
          <width>1920</width>
   <height>1200</height>
          <rate>60</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>no</primary>
      </output>
      <output name="HDMI1">
      </output>
      <output name="DP1">
      </output>
      <output name="HDMI2">
      </output>
      <output name="DP2">
      </output>
      <output name="HDMI3">
      </output>
      <output name="VIRTUAL1">
      </output>
      <output name="VGA-1-1">
      </output>
</configuration>
</monitors>
```

**Comment by VorpalBlade** [comment] 2015-02-22 19:34
How can this still be an issue after 3 years? How hard can it be to add a button, check box or drop down box for setting the primary monitor?

**Comment by trusktr** [comment] 2015-02-22 20:25
@VorpalBlade It's probably really simple, so give it a try. :+1: ;)

**Comment by freed00m** [comment] 2015-03-07 09:43
It must be really hard when this is not implemented till this day :( I hate to have my pluged monitor behave as default one. Grrr. I might do it by my self after graduation, so :D maybe in the next 3 years I'll try to add one.

**Comment by sanderboom** [comment] 2015-03-15 16:00
I've created a shell script to toggle the primary output. I've assigned this to a custom launcher. See: https://github.com/sanderboom/primary-output

**Comment by Master0ne** [comment] 2015-05-10 17:00
This is indeed a bummer, I am just testing Ubuntu Mate 15.04 and can see that this issue is still not resolved. A "Set as Primary" button is a MUST for monitor settings, even Xfce has it for a long time now. This is really disappointing, the mentioned workarounds are just not user friendly enough.

**Comment by jonarmand** [comment] 2015-06-19 22:25
In the panel options uncheck "expand panel", then it is possible to simply move the panel anywhere you want.

Very intuitive... not! But it works.

**Comment by monsta** [comment] 2015-09-07 11:32
Looks like it's fixed now in https://github.com/mate-desktop/mate-control-center/commit/5afb6c09ed3770753eaf068f1a6f998c8d0b9b07.

**Comment by cheater** [comment] 2015-09-07 12:06
Please reopen this issue. I have not reported it as fixed.

**Comment by monsta** [comment] 2015-09-07 12:16
You can actually reopen it yourself since you're the reporter :smile:

**Comment by cheater** [comment] 2015-09-07 15:57
Tyvm. The mobile interface does not show a way of doing this.

I will report once I have this version running.

**Comment by NiceandGently** [comment] 2015-09-16 18:59
https://github.com/mate-desktop/mate-control-center/commit/5afb6c09ed3770753eaf068f1a6f998c8d0b9b07

**Comment by NiceandGently** [comment] 2015-09-16 19:00
@cheater 
any news?

**Comment by oz123** [comment] 2015-10-19 15:00
I also bumped into this issue. This would be great to have a way to specify which screen is the primary, that way the panels are displayed in the correct place.
In the mean while mate-monitor-preferences is useless. It is easier to use xrandr. Here is I use it in the mean while:

**Comment by monsta** [comment] 2015-10-19 15:26
We're waiting for @cheater's reply to confirm whether @clefebvre's commit fixed it...

**Comment by raveit65** [comment] 2015-10-27 17:19
Sorry, no answer from Reporter.
The issue is fixed and we can always re-open it if reporter thinks it isn't fixed.

**Closed by raveit65** 2015-10-27 17:19 UTC
