### ISSUE TITLE
mate-display-properties closes dialog upon clicking "apply"

### ISSUE THREAD

**Issue by balwierz** [mate-desktop/mate-control-center#106] opened 2014-05-30 18:27 UTC
It is a standard assumption that "OK" button applies settings and closes a dialog box, but "Apply" only applies the settings without closing a dialog.

In mate-display-properties "Apply" closes the dialog box.
It is wrong for two reasons:
1) it breaks the aforementioned convention
2) users often play with resolution settings, turn displays on and off and reorganize them until they achieve what looks best for them. It is hard to imaging anyone preferring to launch mate-display-properties several times during this process.

Solution:
- Change the behavior of "Apply" to not to close the window.
- [optional] Add "OK" button which does what "Apply" currently does.

**Comment by stefano-k** [comment] 2015-02-06 13:02
Duplicate of https://github.com/mate-desktop/mate-control-center/issues/48

**Closed by stefano-k** 2015-02-06 13:02 UTC
Labels: confirmed
