### ISSUE TITLE
/usr/bin/mate-display-properties was killed by signal 11

### ISSUE THREAD

**Issue by dmashal** [mate-desktop/mate-control-center#48] opened 2013-04-25 02:54 UTC
Please see https://bugzilla.redhat.com/show_bug.cgi?id=879663

m-c-c seems to have issues with multiple monitors and controlling them. 

I am not sure if this an xrandr bug or not. Stefano can you please advise?

**Comment by NiceandGently** [comment] 2015-01-13 13:03
@stefano-k same as this report.
https://github.com/mate-desktop/mate-control-center/issues/106
Can we focus our work a bit on this reports please?
This is a regression since 1.6.x
Every user in fedora who change the screen resolution after installation will get a alarm from fedora's bug reporting tool.
The list is of users who are affected in downstream report is huge.

**Comment by monsta** [comment] 2015-02-03 10:56
I suspect this is caused by https://bugzilla.gnome.org/show_bug.cgi?id=635380.

**Comment by NiceandGently** [comment] 2015-02-03 15:33
this commit is in gtk3
https://git.gnome.org/browse/gtk+/commit/?id=323df2b2800383832ed3c2e43626f2c6821c33ec
still wondering why this have an effect in gtk2.

**Comment by monsta** [comment] 2015-02-03 18:43
Yes, because they didn't push that commit to GTK+2 branch.

**Comment by monsta** [comment] 2015-02-11 12:07
Ok, I've made a patch for GTK+2 and tested it in Debian (Jessie) and Ubuntu (Precise/Trusty/Utopic).
@NiceandGently also tested it in Fedora a few days ago.

If you use some other distro, you can get the patch from [here](https://launchpadlibrarian.net/197302668/fix_gdk_event_apply_filters.patch) and try it for yourself.

**Comment by NiceandGently** [comment] 2015-02-13 18:43
..end of a long story :)
Patch is pushed to the gtk-2-24 branch upstream.
https://git.gnome.org/browse/gtk+/commit/?h=gtk-2-24&id=ee95f3d7259c0859ce41189b781b4339b4cd64aa
Thanks to monsta and m.clasen.

Marked as can be closed.

**Comment by monsta** [comment] 2015-02-14 07:59
Great! :)

**Comment by stefano-k** [comment] 2015-02-14 14:06
Wonderful! Thank you @monsta and @NiceandGently !!!

**Closed by stefano-k** 2015-02-14 14:06 UTC
Labels: confirmed

**Comment by babak777** [comment] 2015-08-12 22:29
How do I apply the patch to Debian.  I have down loaded gtk2-debdiff.
The reason that I need to apply this patch is that I upgraded from Wheezy to Jessie.  Apparently, they fixed problem on Jessie, but have not in Wheezy.  Since the package has the same version number in Jessie and in Wheezy, it won't get updated on Jessie upgrade.  So I need to apply the patch.  But the question is how to apply the patch?

**Comment by monsta** [comment] 2015-08-13 11:22
>  Since the package has the same version number in Jessie and in Wheezy, it won't get updated on Jessie upgrade.

I don't know which package you mean, but [gtk+2.0](https://packages.debian.org/src:gtk+2.0) is updated during the upgrade just fine as it's newer than in Wheezy. The patch is already in it.

**Comment by babak777** [comment] 2015-08-13 21:37
Hi Monsta,

I used to have mate on Wheezy and I used to be able to run all the programs that ran on gnome.  I upgraded to Jessie.  Now, I am not able run many programs on mate, while I am able to run the same programs on gnome.  For example, when I want to run say synaptic the window is opened and then it crashes.  I did research and it seem to be very similar to symptoms described here.

I described it more detail in another forum : 
http://forums.mate-desktop.org/viewtopic.php?f=5&t=3701&p=11553#p11553

I was thinking to uninstall the mate and reinstall it, but if the problem is with gtk2 then it won't help.
Would you like to find out what went wrong in my system?

Is there a test that we can do to see if the patch is applied?

Thanks,

**Comment by monsta** [comment] 2015-08-13 22:19
> For example, when I want to run say synaptic the window is opened and then it crashes. I did research and it seem to be very similar to symptoms described here.

It doesn't look similar to me. Besides, Synaptic is GTK+3 app.

Your description hints at some more generic upgrade-related problem. Probably the best thing to do is to post a support request at Debian forums.

**Comment by babak777** [comment] 2015-08-13 22:38
Is
http://forums.debian.net/
a good form to post the problem?  If not which forum is the best for posting this problem.

Thanks.

**Comment by monsta** [comment] 2015-08-13 22:58
Never used it, but it's listed on [this wiki page](https://www.debian.org/support.ru.html#web), so it should be ok.

**Comment by monsta** [comment] 2015-08-13 22:59
Never used it, but since it's listed on [the official wiki page](https://www.debian.org/support.html#web), so it should be ok.

**Comment by babak777** [comment] 2015-08-13 23:46
Thanks Monsta,
I will post on that forum.

**Comment by johangwbasson** [comment] 2015-08-25 06:31
I also get the problem on Debian testing. 

    johan@johanba-nb ~ $ mate-display-properties
    [1]    3176 segmentation fault  mate-display-properties

And the debug output:

        johan@johanba-nb ~ $ gdb mate-display-properties
        GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
        Copyright (C) 2014 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
        and "show warranty" for details.
        This GDB was configured as "x86_64-linux-gnu".
        Type "show configuration" for configuration details.
        For bug reporting instructions, please see:
        <http://www.gnu.org/software/gdb/bugs/>.
        Find the GDB manual and other documentation resources online at:
        <http://www.gnu.org/software/gdb/documentation/>.
        For help, type "help".
        Type "apropos word" to search for commands related to "word"...
        Reading symbols from mate-display-properties...Reading symbols from /usr/lib/debug/.build-id/e5/433c1d030dcb2e24e07887bf88e9138dcee350.debug...done.
        done.
        (gdb) run
        Starting program: /usr/bin/mate-display-properties 
        [Thread debugging using libthread_db enabled]
        Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
        [New Thread 0x7fffec5a1700 (LWP 5417)]

        Program received signal SIGSEGV, Segmentation fault.
        list_connected_outputs (total_w=0x7fffffffbd68, total_h=0x7fffffffbd6c, app=<optimized out>) at xrandr-capplet.c:1075
        1075    xrandr-capplet.c: No such file or directory.
        (gdb) 

Distro info:    

    johan@johanba-nb ~ $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux testing (stretch)
    Release:    testing
    Codename:   stretch

Kernel:

    johan@johanba-nb ~ $ uname -a
    Linux johanba-nb 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux

Versions:

    mate-control-center: 1.8.3+dfsg1-2

**Comment by NiceandGently** [comment] 2015-08-25 09:00
Do you have a mix of 1.8 and 1.10 packages?
xrandr changes in mate-desktop package......

**Comment by monsta** [comment] 2015-08-25 14:07
Unrelated but [known issue](https://bugs.debian.org/794676) in testing/unstable, will be fixed after m-c-c is updated to 1.10 there. Please consider checking Debian bug tracker for existing reports before creating a new one.

**Comment by babak777** [comment] 2015-08-26 05:10
Hi johangwbasson,

I had a similar problem. It has to do with a bug in GTK+3.  I found a fix that works for me.  For more info, please follow my posts here:
http://forums.debian.net/viewtopic.php?f=6&t=124130

**Comment by Skamasle** [comment] 2015-09-03 11:20
Same problem here on debian testing:

error 4 in mate-display-properties

So the issue is because mate-display-properties | mate-control-settings version is 1.8 on debian testing so I upgrade it from sid to 1.10 and the problem is solved, are a few ways, wait, upgrade from sid repos or downgrade mate-desktop to 1.8
